name: fluro_dmlzj
description: Dmlzj Fluro is a fork of the popular fluro router for Flutter that adds the option for typed routes\n
version: 2.0.4
homepage: https://github.com/dmlzj/fluro

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
